<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_reCAPTCHA_recaptcha-checkbox-border</name>
   <tag></tag>
   <elementGuidId>cbb97362-8d0e-4747-82db-d819094a5965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='recaptcha-anchor']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I'm not a robot&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>050ce793-9cc8-46b6-b7d5-9bc7672106b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>65c2e44e-f92f-46d5-9b0e-2053d6c9d2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>a7c737ea-e342-4357-a42e-b3728ec0fdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-anchor&quot;)/div[@class=&quot;recaptcha-checkbox-border&quot;]</value>
      <webElementGuid>f6a0af79-3750-415e-bdaa-2abe47247c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/Page_Lapor Folkatech - Login/Page_Lapor Folkatech - Login/iframe_Password_a-ym074ieebjod</value>
      <webElementGuid>95e2a5a8-424f-4fe3-a4be-81407a48da93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>5026549f-b332-4908-9048-4d65ff79ad8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>119bdab1-cc9e-40e5-bb93-397096584ef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
