<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Admin_img-fluid rounded-circle shadow</name>
   <tag></tag>
   <elementGuidId>833da7b3-c122-4638-bf05-fea2bd511b05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded-circle.shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownMenuButton']/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admin Utama Admin Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f596da33-57e9-4453-9b92-65f710219f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lapor.folkatech.com/storage/image_profiles/business+corporate+headshots+027.jpeg</value>
      <webElementGuid>ebecef9e-e801-48c5-a621-59cde823bbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-circle shadow</value>
      <webElementGuid>6102d0d5-d8e6-4ed4-9996-e04af0607ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile Picture</value>
      <webElementGuid>74799a1d-33c7-4535-b226-c937e80b63cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/ul[@class=&quot;navbar-nav ms-auto&quot;]/li[@class=&quot;nav-item dropdown px-3 d-flex align-items-center&quot;]/a[@id=&quot;dropdownMenuButton&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;m-0&quot;]/div[@class=&quot;profile-image-container&quot;]/img[@class=&quot;img-fluid rounded-circle shadow&quot;]</value>
      <webElementGuid>ef7cf251-1654-4233-841f-b3907833cbd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdownMenuButton']/div/div[2]/div/img</value>
      <webElementGuid>984aad9e-5fd9-4a9f-8ec2-c796df2ad78c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile Picture']</value>
      <webElementGuid>e7893d46-fe2d-4216-8bb1-5d072fb12feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2bfc2cef-f0de-4d40-b0b6-3daf13fdd34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lapor.folkatech.com/storage/image_profiles/business+corporate+headshots+027.jpeg' and @alt = 'Profile Picture']</value>
      <webElementGuid>0feceb58-280c-416f-bc38-1cf6654ff10e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
