<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__1</name>
   <tag></tag>
   <elementGuidId>86ddbc0f-10b9-4688-938e-90e489b7b75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#informations-table_ellipsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='informations-table_ellipsis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#informations-table_ellipsis</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>746e87f7-3337-49f9-b80d-22c69a3feb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paginate_button page-item disabled</value>
      <webElementGuid>aa3dfcc7-efc1-4512-8fff-2588f5460002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>informations-table_ellipsis</value>
      <webElementGuid>616c88fe-ff85-4a9a-b0d8-9c8f7b314b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>…</value>
      <webElementGuid>4f9a36f3-7631-480e-8c84-67d819ce3e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;informations-table_ellipsis&quot;)</value>
      <webElementGuid>d26d1d3a-061d-4c37-9223-4a8e59988eeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='informations-table_ellipsis']</value>
      <webElementGuid>c5dd383a-eae6-49dc-88a9-e08da33fc682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='informations-table_paginate']/ul/li[7]</value>
      <webElementGuid>2cd18482-e254-4842-bf0f-56d822fc2853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 76 to 100 of 5,143 entries'])[1]/following::li[7]</value>
      <webElementGuid>2baf7594-3a14-4deb-bc6b-3e2e703aeda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[25]/following::li[7]</value>
      <webElementGuid>5c7e2b72-5a76-4b0e-9991-54fcebf71f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>ce6623a8-5ed7-4332-8fe9-95ddd857ba73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'informations-table_ellipsis' and (text() = '…' or . = '…')]</value>
      <webElementGuid>bf981061-62a8-4ec8-90af-ec85833e1355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
