<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Admin_img-fluid rounded-circle shadow</name>
   <tag></tag>
   <elementGuidId>79920336-d0fd-4ca8-86f2-5c3f991389d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded-circle.shadow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownMenuButton']/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Admin Utama Admin Profile Picture&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>da3f3f6a-486b-4055-b652-3dcb7979c520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lapor.folkatech.com/storage/image_profiles/business+corporate+headshots+027.jpeg</value>
      <webElementGuid>d917eeaa-d876-43b9-9de4-a2099d7dc028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded-circle shadow</value>
      <webElementGuid>9ab201b6-51ea-401f-aaad-8437df833823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile Picture</value>
      <webElementGuid>22fe3a0e-4107-49a3-a3a0-e2b8d570921c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownMenuButton&quot;)/div[@class=&quot;d-flex align-items-center&quot;]/div[@class=&quot;m-0&quot;]/div[@class=&quot;profile-image-container&quot;]/img[@class=&quot;img-fluid rounded-circle shadow&quot;]</value>
      <webElementGuid>7135ee7b-92d0-4312-aea2-2fa966188ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdownMenuButton']/div/div[2]/div/img</value>
      <webElementGuid>0894c02c-e49b-4ac6-bfec-0acbe9e00c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile Picture']</value>
      <webElementGuid>280047d0-321c-4b74-9fae-8c4cbe303605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>24b401cc-5339-4b33-a592-54cbdb7e6a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lapor.folkatech.com/storage/image_profiles/business+corporate+headshots+027.jpeg' and @alt = 'Profile Picture']</value>
      <webElementGuid>4d0922f3-20fe-4149-b130-8f8f7848747d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
