<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-u1vfjpwwp4ra</name>
   <tag></tag>
   <elementGuidId>879de985-cf06-46e6-a410-c318a59a90a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-u1vfjpwwp4ra&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-u1vfjpwwp4ra']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-u1vfjpwwp4ra&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>74a6ed60-c2c6-43d5-891e-33faccdb64a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>d6b55a75-1f2a-4879-ac68-947dfbe0a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>bacb4955-7b1e-4335-ab07-6abdfe32dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>3ea72682-aac1-4f65-bb7a-671b4136fd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>5533f233-7724-4a89-b00d-bfb332e143b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-u1vfjpwwp4ra</value>
      <webElementGuid>08c03abb-2949-4bb4-8e65-a19b83f72d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fbda4023-120e-4e2f-a2cd-1da0f70cc38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>62eaa277-07a7-4d95-ae5b-2e2d96893ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>af33793d-9543-4c8d-a4de-0f38dc96f48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;co=aHR0cHM6Ly9sYXBvci5mb2xrYXRlY2guY29tOjQ0Mw..&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;cb=5tckdhfap0qg</value>
      <webElementGuid>54d60275-cfee-4224-8ae1-5cd079d39518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;vh-100&quot;]/div[@class=&quot;costume-container px-3 mx-auto w-100&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 d-flex justify-content-center align-items-center&quot;]/div[@class=&quot;card card-plain&quot;]/div[@class=&quot;col-md-10 card-body&quot;]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>3f984c63-d178-4cde-9bea-d53ccccd0cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-u1vfjpwwp4ra']</value>
      <webElementGuid>72966d2f-5b03-4340-9afb-4578b9faacd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>729f8af2-4f38-4f92-8496-07d066bf50c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-u1vfjpwwp4ra' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf&amp;co=aHR0cHM6Ly9sYXBvci5mb2xrYXRlY2guY29tOjQ0Mw..&amp;hl=en&amp;v=IyZ984yGrXrBd6ihLOYGwy9X&amp;size=normal&amp;cb=5tckdhfap0qg']</value>
      <webElementGuid>a88f9ee8-67bd-43d7-abc6-b42dde9303b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
