<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>99c9f000-1f5f-4b51-bb61-6b1e33d0ccec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d603d92f-09bb-489e-ba62-11aa3543396e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>a94cf4a1-aa76-4d58-84fc-cd1ffcb20823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>c998dd51-28b7-4ffc-aeb6-586ace7f485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>4706bb3e-687b-47eb-9229-e6a237b05e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-qu9hi0aet56q</value>
      <webElementGuid>955e6613-51ba-474a-b71d-ba78383cefb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[3]/div/div/img</value>
      <webElementGuid>d8ce9728-dac1-48ee-a7f8-74d440ba9ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[15]</value>
      <webElementGuid>d7a50e24-be17-4539-a1e1-0d16a17d3305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[3]/div/div/img</value>
      <webElementGuid>2b1b22ae-86a3-4154-bc7f-9543a7dd09f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>73603e6a-4092-41ff-add0-03e9966e537e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
