<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>561fe95d-c997-45c3-96fb-a46901dcdd65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e63e31a-85e8-4e54-9bff-a756b9565c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>abbf680b-d121-4961-b882-54cd223c70ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>802c7d90-ace1-489c-b7c4-ed7100b6f8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>0d47ad09-634e-4423-b449-086618fc85c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-qu9hi0aet56q</value>
      <webElementGuid>cb41a815-0347-4221-a3b4-834c050eeb69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>617164d6-3bc0-44ee-b8a3-ced6018034d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[6]</value>
      <webElementGuid>877b59e0-6d53-42cb-ba93-7be437a1b93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>ea1ed46c-3e1d-4b15-b9c4-8f2fb53c2b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>43e89ae8-38e7-405a-957c-81a55fec2be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
