<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>5c12da8e-3a55-4ad9-b9b4-e49c94acd95b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52424911-2c8d-4d47-beef-472a5d434a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>33debb93-b35d-4320-a312-f0b6115b2cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>4fd6b0f8-531c-4968-9874-691eaeb1af39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>7fd63e41-bb32-4530-b682-84e692718041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-qu9hi0aet56q</value>
      <webElementGuid>99134e6c-7602-472f-b580-33d8886e337b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      <webElementGuid>619df3f4-cf5b-4b53-955e-eb9f0e50b9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[14]</value>
      <webElementGuid>0766a272-2962-4e8d-8476-a1144f04a4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/img</value>
      <webElementGuid>0cfebb9e-5314-4798-a5ea-f5fceb273874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>8252902f-785b-46de-bcd1-1ec6d837dd22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
