<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>8af010e6-223b-45fe-a7b7-c0012ddf485e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bffbadb2-3d56-41ba-a5a5-7022426e6efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>b169b86b-7683-4d89-9496-93b3a911342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>7bb438b5-a141-4f74-b06b-5db0856260fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>a909279b-4d03-44ce-8154-0771d0a339af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-qu9hi0aet56q</value>
      <webElementGuid>aa6d4327-43e5-4320-9133-93751bf9034e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td/div/div/img</value>
      <webElementGuid>72d51c1a-3f11-40e1-a33e-280bfc1c88f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[13]</value>
      <webElementGuid>9492b3fb-2172-41b6-9b08-1c8eb2c70b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/img</value>
      <webElementGuid>243b2be2-cc12-4ed8-98e9-d91d01f4fb84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>6dd56d0d-dda5-431c-b510-10e65107ee3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
