<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_bicycles_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>29b54a4b-ba38-4635-b675-7914884942ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72d1c0ba-5d55-474b-a287-e123df39bb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>6d184be0-660c-4fb6-a51b-ab96070f4765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf</value>
      <webElementGuid>679a9e30-a29a-460d-a6b4-4001a4a119dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>6314330c-5fc5-4bb0-ae03-f54b0c84c06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Web Browser/Page_Lapor Folkatech - Login/iframe_html1body1div1div4iframe1_c-qu9hi0aet56q</value>
      <webElementGuid>acfcb98a-216e-4474-aeb1-9e882646d97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[3]/div/div/img</value>
      <webElementGuid>815297e1-7cbe-4aa3-ab80-90c8a3ed48de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf')])[11]</value>
      <webElementGuid>f45f484d-67b6-4370-8285-9ac0b6fa3564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/div/img</value>
      <webElementGuid>d8d165bc-f5b9-4906-98a5-eb2d4c2f4d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA4E9poGyhJbW7j_gsS22JFYzWrM_c1NC7tLsuevFBkRdZVmY09faypc_gLsSAzcaufhSodDGuQsLJhp0JwRZWfM0hwK_EGmwaHs33WaAFoJvYeOhHJa16sVShpkyfdDCaVHfsPwlHFSb43QAx2yhYXPrmjewN6cJbkf3hQ0AtgywIefwHrqjAELMApgo5Tbw0lU1c0KUQgd7BV7EhTpdCRUsL3L2g&amp;k=6Lefis4qAAAAAP3zI-ZCPSQPjeLQEDO9KK8CEZXf']</value>
      <webElementGuid>3926c428-98cf-4fbd-869a-accbd64ed4f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
