<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Laporan</name>
   <tag></tag>
   <elementGuidId>11b3c869-a604-41cc-87da-f2fe360d3ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div/ol/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#navbar >> internal:role=link[name=&quot;Laporan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5e262f4-ffe8-41bc-8ca0-e9237289316a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://lapor.folkatech.com/admin/report</value>
      <webElementGuid>52e0ee6d-a6a5-4ae8-8a31-6467d0468852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporan</value>
      <webElementGuid>6fbb6f97-e85b-489a-9032-705b33ff3654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;flex-item align-items-center pt-3 me-auto&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item&quot;]/a[1]</value>
      <webElementGuid>64902196-ef78-4d77-8ed6-4bf42d8332b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/ol/li[2]/a</value>
      <webElementGuid>1184bb0f-2fb4-4122-9a20-6581acf1ac49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Laporan')]</value>
      <webElementGuid>f4817c2d-a6d8-421d-ad9d-50128b8fb83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>59947982-01f1-4413-a15b-59d043f9463f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Pengguna'])[1]/following::a[2]</value>
      <webElementGuid>364afcf4-a78e-490d-9f2e-458f945255cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Laporan'])[2]/preceding::a[1]</value>
      <webElementGuid>4f030fda-79fd-403c-8dad-c0e32b9fde51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Utama'])[1]/preceding::a[1]</value>
      <webElementGuid>7fb04a53-953d-4a09-831a-9b85c15fc23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://lapor.folkatech.com/admin/report')])[2]</value>
      <webElementGuid>ec24af75-157c-4c4d-91da-cddd49da6caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>f027523b-e340-4e93-aeb9-b4cc2ed063e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://lapor.folkatech.com/admin/report' and (text() = 'Laporan' or . = 'Laporan')]</value>
      <webElementGuid>5ba20ffb-9cb0-4c3b-ba63-509b83953005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
